name: Generate Pacman Animation

on:
  schedule:
    - cron: "0 */12 * * *" # a cada 12 horas corretamente

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate pacman-contribution-graph.svg
        id: pacman
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Deploy to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: "Update pacman contribution graph"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
